### PR TITLE
Add support for Shapely 2.0

### PR DESCRIPTION
**Pull request by fitodic**
Shapely will drop support for setting custom attributes starting from
version 2.0. The geometry would be made available via the
`Centerline.geometry` attribute instead.

- [x] Add support for Shapely 2.x
- [x] Migrate CI from Travis to GitHub Actions
- [x] Enable releases by Github Actions
- [x] Check the error raised by `fiona` on Python 3.10

Fixes: https://github.com/fitodic/centerline/issues/29 https://github.com/fitodic/centerline/issues/35 https://github.com/fitodic/centerline/issues/36

### CODE REVIEW

**Comment by mrazzaq19** [comment]
Hello there, 
Following your guideline to run the python:
from shapely.geometry import Polygon
from centerline.geometry import Centerline

polygon = Polygon([[0, 0], [0, 4], [4, 4], [4, 0]])
attributes = {"id": 1, "name": "polygon", "valid": True}

centerline = Centerline(polygon, **attributes)
centerline.id == 1
True
centerline.name
'polygon'
centerline.geoms
<shapely.geometry.base.GeometrySequence object at 0x7f7d24116210>
---
How do we visualize the output?? and how to read the polygone.shp file??

**Comment by fitodic** [comment]
Hello @mrazzaq19,

to achieve that, you'll have to use other 3rd party libraries. For [visualization](https://stackoverflow.com/a/56140178), you can take a look at [matplotlib](https://matplotlib.org/), whereas to [read a shapefile](https://gis.stackexchange.com/a/113808), you can take a look at [fiona](https://fiona.readthedocs.io/en/latest/) or at the [`create_centerlines`](https://github.com/fitodic/centerline/blob/master/src/centerline/converters.py#L85) command.

**Comment by mrazzaq19** [comment]
Dear Filip,
First of all thanks a lot for the prompt reply, appreciated. 
I have done with reading file.shp and visualizing it. 
1. How can one load and see the vironoi diagram figure you shared on 
(https://centerline.readthedocs.io/en/latest/)?

2. Command-line interface: How does that work?

4. Python: For this, I got this out
<shapely.geometry.base.GeometrySequence at 0x7f918f448a50> How do I save and visualize this?


shape

I want to draw a centerline through this geometry:
test_im

This must be a toy problem for you but means a lot

**Comment by fitodic** [comment]
> How can one load and see the vironoi diagram figure you shared on

You can take a look at [QGIS](https://www.qgis.org/en/site/). I used that to visualize the diagrams by [importing the shapefile](https://www.spotzi.com/en/about/help-center/how-to-import-a-shapefile-into-qgis/).

> Command-line interface: How does that work?

It's a terminal that works on [Windows](https://www.makeuseof.com/tag/a-beginners-guide-to-the-windows-command-line/) and [Linux](https://ubuntu.com/tutorials/command-line-for-beginners#1-overview). You open it, activate the environment the package is installed in and run the `create_centerlines` [command](https://ubuntu.com/tutorials/command-line-for-beginners#1-overview):

```bash
create_centerlines /path/to/your/input.shp /path/to/your/output.shp
```

That command will take in all the areas your shapefile has, create centerlines and save them into the output shapefile.

> Python: For this, I got this out... How do I save and visualize this?

It's what the `create_centerlines` [does for you](https://github.com/fitodic/centerline/blob/master/src/centerline/converters.py#L101), but basically you'd have to open a new file and write the centerline data to it:

```python

```with fiona.open(
    dst,
    mode="w",
    driver=driver.GetName(),
    schema=schema,
    crs=source_file.crs,
    encoding=source_file.encoding,
) as destination_file:
    for record in source_file:
        geom = record.get("geometry")
        input_geom = shape(geom)
  
        attributes = record.get("properties")
        try:
            centerline_obj = Centerline(input_geom, interpolation_distance, **attributes)
        except (InvalidInputTypeError, TooFewRidgesError) as error:
            logging.warning(error)
            continue
  
        centerline_dict = {
            "geometry": mapping(centerline_obj),
            "properties": {
                k: v
                for k, v in centerline_obj.__dict__.items()
                if k in attributes.keys()
            },
        }
  
        destination_file.write(centerline_dict)
```

**Comment by mrazzaq19** [comment]
Thanks, 
`create_centerlines /path/to/your/input.shp /path/to/your/output.shp`
works now and the zipped shp folder is visualized to see the centerlines in QGIS.

- Writing the centerline data: I didn't get that! how to create after saving? is it through QGIS or command line command?? 
- `create_centerlines /path/to/your/input.shp /path/to/your/output.geojson` is it for creating geojson file. right!!!
- Is it possible to construct a centerline: considering the inner rectangle as a hole? 
check2box

Many thanks for your guidance and prompt responses.

**Comment by fitodic** [comment]
> Writing the centerline data: I didn't get that! how to create after saving? is it through QGIS or command line command??

It really depends on your use-case. If you all your data in a shapefile or some other format, than the `create_centerlines` command should be enough. If you want to customize a part of the process, you'll need to load the areas, create `Centerline` objects and save them by opening a file and writing to it.

> Is it possible to construct a centerline: considering the inner rectangle as a hole?

Yes, the `Centerline` class handles those cases as well. There's nothing special about them, but you may end up with certain spruces that stick out (depending on the level of detail) that you may want to delete manually using QGIS.

**Comment by mrazzaq19** [comment]
That is what I get. Even the inner rectangle gets a centerline, Which I don't want. 

mytest

Thanks for your interest.

**Comment by mrazzaq19** [comment]
rec_centerlin
--
A bit closer: What I did is I created the image to make the inner rectangle transparent. then load on QGIS and convert that to *.shp file. 

> created the centerline through the command line and again visualize that on QGIS. 

> What should I do next to save the centerlines only?? This thing isn,t yet clear to me.

appreciated.

**Comment by mrazzaq19** [comment]
can we import and convert vector files to shape files? for instances: ps to shp? and can we construct multipolygones based on vector data e.g. 
'polygon1 = Polygon([[0,0] , [16, 0], [16, 10], [0, 10],     [4, 3], [4, 7], [8, 7], [8, 3]           ])' ??

**Comment by fitodic** [comment]
Yes, if the hole is an area, it'll get its own centerline that can be manually removed using QGIS.

The `create_centerlines` command should support all [vector drivers provided by OGR](https://gdal.org/drivers/vector/index.html), but I only used shapefiles and geojson until now.

**Comment by fitodic** [comment]
Fixes #29 #35 #36

**Pull request merged**
